%% SYS800 - Reconnaissance de formes et inspection
% M'Hand Kedjar - December 2016

% Get the projected data to the 1st n components
    train_features_acp_projected = get_acp_projection(train_features ,...
        train_features_acp.vec_p,...
        train_features_acp.M, ...
        n_components);
    
    test_features_acp_projected  = get_acp_projection(test_features ,...
        train_features_acp.vec_p,...
        mean(test_features), ...
        n_components);