%% SYS800 - Reconnaissance de formes et inspection
% M'Hand Kedjar - December 2016

 %% K-NN
    % % For Test Database 
     disp('Processing K-NN for the test database') 
    [err_KNN_Test , cm_KNN_Test, knnTestRunningTime, prediction_KNN_Test] = Classify_KNN_Test(train_features_acp_projected, ...
        train_labels, ...
        test_features_acp_projected, ...
        test_labels, ...
        n_classes, ...
        k_optimal);