%% SYS800 - Reconnaissance de formes et inspection
% M'Hand Kedjar - December 2016

  %% SVM
    % For the validation database
    disp('Processing LIBSVM for the validation database') 
    [err_LIBSVM_Val, cm_LIBSVM_Val, libsvm_optim_params, libsvmValRunningTime, prediction_LIBSVM_Val] =...
        Classify_LIBSVM_Val(train_features_acp_projected, ...
                         train_labels, ...
                         indexLearning,...
                         indexValidation,...
                         n_classes);