%% SYS800 - Reconnaissance de formes et inspection
% M'Hand Kedjar - December 2016

   %% SVM
    % For the validation database
    disp('Processing SVM for the validation database') 
    [err_SVM_Val, cm_SVM_Val, optim_params, svmValRunningTime, prediction_SVM_Val] =...
        Classify_SVM_Val(train_features_acp_projected, ...
                         train_labels, ...
                         indexLearning,...
                         indexValidation,...
                         n_classes);